apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-impersonate
rules:
- apiGroups:
  - ""
  resourceNames:
  - jason.quek@devoteam.com
  - andytzou@google.com
  - 74668819743@cloudbuild.gserviceaccount.com
  - gitlabbuild@anthos-sandbox-256114.iam.gserviceaccount.com
  resources:
  - users
  verbs:
  - impersonate
