apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-impersonate
rules:
- apiGroups:
  - ""
  resourceNames:
  - jason.quek@devoteam.com
  - andytzou@google.com
  resources:
  - users
  verbs:
  - impersonate