kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-sres
subjects:
- kind: User
  name: sre@internalservices.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prod-sre
  apiGroup: rbac.authorization.k8s.io