kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staging-developers
subjects:
- kind: User
  name: developers@internalservices.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: staging-developer
  apiGroup: rbac.authorization.k8s.io