# The dev-developer role is used for developers to work with clusters and also applied to clusters labelled as dev
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-developer
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-dev
rules:
- apiGroups: [""]
  resources: ["pod", "service", "daemonset", "deployment", "replicaset", "statefulset", "job", "cronjobs"]
  verbs: ["create", "get", "watch", "list", "update", "patch", "delete", "deletecollection"]
