# The prod-developerr role is used for developerrs to work with clusters and also applied to clusters labelled as prod
# Developers should only be able to read objects in prod environments. Changes should be applied via pull requests.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-developer
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-prod
rules:
- apiGroups: [""]
  resources: ["pod", "service", "daemonset", "deployment", "replicaset", "statefulset", "job", "cronjobs"]
  verbs: ["get", "watch", "list"]
