# The staging-developer role is used for developers to work with clusters and also applied to clusters labelled as staging
# Developers should only be able to read objects in staging environments. Changes should be applied via pull requests.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staging-developer
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-staging
rules:
- apiGroups: [""]
  resources: ["pod", "service", "daemonset", "deployment", "replicaset", "statefulset", "job", "cronjobs"]
  verbs: ["get", "watch", "list"]
