# The prod-sre role is used for SREs to work with clusters and also applied to clusters labelled as prod
# SREs should be able to read and write in prod environments. Changes should be applied via pull requests.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-sre
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-prod
rules:
- apiGroups: [""]
  resources: ["pod", "service", "daemonset", "deployment", "replicaset", "statefulset", "job", "cronjobs"]
  verbs: ["create", "get", "watch", "list", "update", "patch", "delete", "deletecollection"]
